// Auto-generated type stubs for backend feature containers
declare const _stub: any;
export default _stub;
export const CacheKeys: any;
export type CacheKeys = any;
export const CacheTTL: any;
export type CacheTTL = any;
export const CategoryTransformer: any;
export type CategoryTransformer = any;
export const ContentStatus: any;
export type ContentStatus = any;
export const ContentTemplateRepository: any;
export type ContentTemplateRepository = any;
export const ContentTemplateService: any;
export type ContentTemplateService = any;
export const Customer: any;
export type Customer = any;
export const FilterFieldConfigMap: any;
export type FilterFieldConfigMap = any;
export const Order: any;
export type Order = any;
export const OrderActivityLog: any;
export type OrderActivityLog = any;
export const OrderFeeItem: any;
export type OrderFeeItem = any;
export const OrderProduct: any;
export type OrderProduct = any;
export const OrderStatus: any;
export type OrderStatus = any;
export const OrderTrackingCheckpoint: any;
export type OrderTrackingCheckpoint = any;
export const PartnerStatus: any;
export type PartnerStatus = any;
export const PostPolicy: any;
export type PostPolicy = any;
export const PostTransformer: any;
export type PostTransformer = any;
export const RateCardType: any;
export type RateCardType = any;
export const RateItemType: any;
export type RateItemType = any;
export const RedirectRepository: any;
export type RedirectRepository = any;
export const RedirectService: any;
export type RedirectService = any;
export const ServiceType: any;
export type ServiceType = any;
export const ShippingMethod: any;
export type ShippingMethod = any;
export const ShippingOrigin: any;
export type ShippingOrigin = any;
export const TaxonomyRepository: any;
export type TaxonomyRepository = any;
export const TaxonomyService: any;
export type TaxonomyService = any;
export const USERNAME_REGEX: any;
export type USERNAME_REGEX = any;
export const USERNAME_VALIDATION_MESSAGE: any;
export type USERNAME_VALIDATION_MESSAGE = any;
export const UserStatus: any;
export type UserStatus = any;
export const UserTransformer: any;
export type UserTransformer = any;
export const WORLD_LANGUAGES: any;
export type WORLD_LANGUAGES = any;
export const buildPrismaWhere: any;
export type buildPrismaWhere = any;
export const checkDuplicates: any;
export type checkDuplicates = any;
export const checkHealth: any;
export type checkHealth = any;
export const contentLockService: any;
export type contentLockService = any;
export const defaultTemplates: any;
export type defaultTemplates = any;
export const exportContent: any;
export type exportContent = any;
export const findPostByTranslatedSlug: any;
export type findPostByTranslatedSlug = any;
export const fullTextSearch: any;
export type fullTextSearch = any;
export const getAdministrativeService: any;
export type getAdministrativeService = any;
export const getAnalyticsService: any;
export type getAnalyticsService = any;
export const getApiKeyRepository: any;
export type getApiKeyRepository = any;
export const getAuditService: any;
export type getAuditService = any;
export const getAuthService: any;
export type getAuthService = any;
export const getBulkActionService: any;
export type getBulkActionService = any;
export const getCategoryService: any;
export type getCategoryService = any;
export const getCommentService: any;
export type getCommentService = any;
export const getContactService: any;
export type getContactService = any;
export const getCustomFieldService: any;
export type getCustomFieldService = any;
export const getCustomerAuthService: any;
export type getCustomerAuthService = any;
export const getCustomerGroupService: any;
export type getCustomerGroupService = any;
export const getCustomerPackageService: any;
export type getCustomerPackageService = any;
export const getCustomerReceiverService: any;
export type getCustomerReceiverService = any;
export const getCustomerRepository: any;
export type getCustomerRepository = any;
export const getCustomerSenderService: any;
export type getCustomerSenderService = any;
export const getCustomerService: any;
export type getCustomerService = any;
export const getCustomerTokenService: any;
export type getCustomerTokenService = any;
export const getDashboardStats: any;
export type getDashboardStats = any;
export const getDatabaseMaintenanceService: any;
export type getDatabaseMaintenanceService = any;
export const getDeviceTokenService: any;
export type getDeviceTokenService = any;
export const getExportService: any;
export type getExportService = any;
export const getHsCodeService: any;
export type getHsCodeService = any;
export const getImportService: any;
export type getImportService = any;
export const getLanguageRepository: any;
export type getLanguageRepository = any;
export const getLanguageService: any;
export type getLanguageService = any;
export const getMediaFileService: any;
export type getMediaFileService = any;
export const getMediaFolderService: any;
export type getMediaFolderService = any;
export const getNotificationService: any;
export type getNotificationService = any;
export const getNotificationSettingService: any;
export type getNotificationSettingService = any;
export const getNotificationTemplateService: any;
export type getNotificationTemplateService = any;
export const getOrderRepository: any;
export type getOrderRepository = any;
export const getOrderService: any;
export type getOrderService = any;
export const getPackingService: any;
export type getPackingService = any;
export const getPageService: any;
export type getPageService = any;
export const getPartnerService: any;
export type getPartnerService = any;
export const getPostService: any;
export type getPostService = any;
export const getRateCardRepository: any;
export type getRateCardRepository = any;
export const getRateCardService: any;
export type getRateCardService = any;
export const getRelatedPosts: any;
export type getRelatedPosts = any;
export const getRevisionService: any;
export type getRevisionService = any;
export const getRoleService: any;
export type getRoleService = any;
export const getScheduledNotificationService: any;
export type getScheduledNotificationService = any;
export const getSeoMetaService: any;
export type getSeoMetaService = any;
export const getSettingService: any;
export type getSettingService = any;
export const getSystemDiagnosticsService: any;
export type getSystemDiagnosticsService = any;
export const getTagService: any;
export type getTagService = any;
export const getTopupTransactionService: any;
export type getTopupTransactionService = any;
export const getTranslationService: any;
export type getTranslationService = any;
export const getUserManagementService: any;
export type getUserManagementService = any;
export const getWebhookService: any;
export type getWebhookService = any;
export const getWorkflowService: any;
export type getWorkflowService = any;
export const importContent: any;
export type importContent = any;
export const mapToAdminOrderDetailResponse: any;
export type mapToAdminOrderDetailResponse = any;
export const mapToAdminOrderSummaryResponse: any;
export type mapToAdminOrderSummaryResponse = any;
export const overlayCategoryTranslations: any;
export type overlayCategoryTranslations = any;
export const overlayPageTranslation: any;
export type overlayPageTranslation = any;
export const overlayPageTranslations: any;
export type overlayPageTranslations = any;
export const overlayPostTranslation: any;
export type overlayPostTranslation = any;
export const overlayPostTranslations: any;
export type overlayPostTranslations = any;
export const overlayTagTranslations: any;
export type overlayTagTranslations = any;
export const prisma: any;
export type prisma = any;
export const registerEventListeners: any;
export type registerEventListeners = any;
export const responseCache: any;
export type responseCache = any;

export namespace Prisma {
  export type DbNull = any;
  export const DbNull: any;
  export type Decimal = any;
  export const Decimal: any;
  export type InputJsonValue = any;
  export const InputJsonValue: any;
  export type JsonValue = any;
  export const JsonValue: any;
  export type OrderImportWhereInput = any;
  export const OrderImportWhereInput: any;
  export type SortOrder = any;
  export const SortOrder: any;
  export type TransactionClient = any;
  export const TransactionClient: any;
}
export const Prisma: any;
