// Auto-generated type stubs for backend feature containers
declare const _stub: any;
export default _stub;
export const CacheKeys: any;
export type CacheKeys = any;
export const CacheTTL: any;
export type CacheTTL = any;
export const CategoryTransformer: any;
export type CategoryTransformer = any;
export const ContentStatus: any;
export type ContentStatus = any;
export const ContentTemplateRepository: any;
export type ContentTemplateRepository = any;
export const ContentTemplateService: any;
export type ContentTemplateService = any;
export const Customer: any;
export type Customer = any;
export const FilterFieldConfigMap: any;
export type FilterFieldConfigMap = any;
export const Order: any;
export type Order = any;
export const OrderActivityLog: any;
export type OrderActivityLog = any;
export const OrderFeeItem: any;
export type OrderFeeItem = any;
export const OrderProduct: any;
export type OrderProduct = any;
export const OrderStatus: any;
export type OrderStatus = any;
export const OrderTrackingCheckpoint: any;
export type OrderTrackingCheckpoint = any;
export const PartnerStatus: any;
export type PartnerStatus = any;
export const PostPolicy: any;
export type PostPolicy = any;
export const PostTransformer: any;
export type PostTransformer = any;
export const RateCardType: any;
export type RateCardType = any;
export const RateItemType: any;
export type RateItemType = any;
export const RedirectRepository: any;
export type RedirectRepository = any;
export const RedirectService: any;
export type RedirectService = any;
export const ServiceType: any;
export type ServiceType = any;
export const ShippingMethod: any;
export type ShippingMethod = any;
export const ShippingOrigin: any;
export type ShippingOrigin = any;
export const TaxonomyRepository: any;
export type TaxonomyRepository = any;
export const TaxonomyService: any;
export type TaxonomyService = any;
export const USERNAME_REGEX: any;
export type USERNAME_REGEX = any;
export const USERNAME_VALIDATION_MESSAGE: any;
export type USERNAME_VALIDATION_MESSAGE = any;
export const UserStatus: any;
export type UserStatus = any;
export const UserTransformer: any;
export type UserTransformer = any;
export const WORLD_LANGUAGES: any;
export type WORLD_LANGUAGES = any;
export const Workbook: any;
export type Workbook = any;
export const acquire: any;
export type acquire = any;
export const addIssue: any;
export type addIssue = any;
export const addItem: any;
export type addItem = any;
export const addRow: any;
export type addRow = any;
export const addService: any;
export type addService = any;
export const addToBlacklist: any;
export type addToBlacklist = any;
export const addToBlacklistBulk: any;
export type addToBlacklistBulk = any;
export const addTrackingCheckpoint: any;
export type addTrackingCheckpoint = any;
export const addWorksheet: any;
export type addWorksheet = any;
export const all: any;
export type all = any;
export const allSettled: any;
export type allSettled = any;
export const any: any;
export type any = any;
export const approve: any;
export type approve = any;
export const archivePost: any;
export type archivePost = any;
export const array: any;
export type array = any;
export const assignMembers: any;
export type assignMembers = any;
export const assignTo: any;
export type assignTo = any;
export const blacklistToken: any;
export type blacklistToken = any;
export const boolean: any;
export type boolean = any;
export const buildPrismaWhere: any;
export type buildPrismaWhere = any;
export const bulkCategoryAssign: any;
export type bulkCategoryAssign = any;
export const bulkDeleteCategories: any;
export type bulkDeleteCategories = any;
export const bulkDeletePages: any;
export type bulkDeletePages = any;
export const bulkDeletePosts: any;
export type bulkDeletePosts = any;
export const bulkDeleteTags: any;
export type bulkDeleteTags = any;
export const bulkSet: any;
export type bulkSet = any;
export const bulkStatusCustomers: any;
export type bulkStatusCustomers = any;
export const bulkStatusPosts: any;
export type bulkStatusPosts = any;
export const calculate: any;
export type calculate = any;
export const calculateFreight: any;
export type calculateFreight = any;
export const calculateOrderFreight: any;
export type calculateOrderFreight = any;
export const changePassword: any;
export type changePassword = any;
export const check: any;
export type check = any;
export const checkDuplicates: any;
export type checkDuplicates = any;
export const checkHealth: any;
export type checkHealth = any;
export const checkUsernameAvailability: any;
export type checkUsernameAvailability = any;
export const clear: any;
export type clear = any;
export const clonePost: any;
export type clonePost = any;
export const contentLockService: any;
export type contentLockService = any;
export const count: any;
export type count = any;
export const countByOwner: any;
export type countByOwner = any;
export const create: any;
export type create = any;
export const createCategory: any;
export type createCategory = any;
export const createComment: any;
export type createComment = any;
export const createCustomer: any;
export type createCustomer = any;
export const createCustomerGroup: any;
export type createCustomerGroup = any;
export const createFolder: any;
export type createFolder = any;
export const createGroup: any;
export type createGroup = any;
export const createLanguage: any;
export type createLanguage = any;
export const createOrder: any;
export type createOrder = any;
export const createPage: any;
export type createPage = any;
export const createPartner: any;
export type createPartner = any;
export const createPost: any;
export type createPost = any;
export const createRole: any;
export type createRole = any;
export const createTag: any;
export type createTag = any;
export const createUser: any;
export type createUser = any;
export const createWebhook: any;
export type createWebhook = any;
export const date: any;
export type date = any;
export const defaultTemplates: any;
export type defaultTemplates = any;
export const del: any;
export type del = any;
export const deleteAuditLog: any;
export type deleteAuditLog = any;
export const deleteCategory: any;
export type deleteCategory = any;
export const deleteComment: any;
export type deleteComment = any;
export const deleteCustomer: any;
export type deleteCustomer = any;
export const deleteCustomerGroup: any;
export type deleteCustomerGroup = any;
export const deleteFile: any;
export type deleteFile = any;
export const deleteFiles: any;
export type deleteFiles = any;
export const deleteFolder: any;
export type deleteFolder = any;
export const deleteGroup: any;
export type deleteGroup = any;
export const deleteLanguage: any;
export type deleteLanguage = any;
export const deleteMany: any;
export type deleteMany = any;
export const deleteModelFields: any;
export type deleteModelFields = any;
export const deleteNotification: any;
export type deleteNotification = any;
export const deletePage: any;
export type deletePage = any;
export const deletePartner: any;
export type deletePartner = any;
export const deletePost: any;
export type deletePost = any;
export const deleteRequestLog: any;
export type deleteRequestLog = any;
export const deleteRole: any;
export type deleteRole = any;
export const deleteService: any;
export type deleteService = any;
export const deleteSubmission: any;
export type deleteSubmission = any;
export const deleteTag: any;
export type deleteTag = any;
export const deleteTranslation: any;
export type deleteTranslation = any;
export const deleteUser: any;
export type deleteUser = any;
export const deleteWebhook: any;
export type deleteWebhook = any;
export const dispatch: any;
export type dispatch = any;
export const duplicate: any;
export type duplicate = any;
export const duplicateGroup: any;
export type duplicateGroup = any;
export const eachCell: any;
export type eachCell = any;
export const enterWith: any;
export type enterWith = any;
export const entries: any;
export type entries = any;
export const exec: any;
export type exec = any;
export const exportAll: any;
export type exportAll = any;
export const exportCategories: any;
export type exportCategories = any;
export const exportContent: any;
export type exportContent = any;
export const exportCustomers: any;
export type exportCustomers = any;
export const exportGroups: any;
export type exportGroups = any;
export const exportPages: any;
export type exportPages = any;
export const exportPosts: any;
export type exportPosts = any;
export const exportSettings: any;
export type exportSettings = any;
export const exportTags: any;
export type exportTags = any;
export const findActivityLogs: any;
export type findActivityLogs = any;
export const findAuditLogs: any;
export type findAuditLogs = any;
export const findByCode: any;
export type findByCode = any;
export const findByHashedKey: any;
export type findByHashedKey = any;
export const findById: any;
export type findById = any;
export const findByLocale: any;
export type findByLocale = any;
export const findDefault: any;
export type findDefault = any;
export const findMany: any;
export type findMany = any;
export const findManyByOwner: any;
export type findManyByOwner = any;
export const findOverlappingRateCards: any;
export type findOverlappingRateCards = any;
export const findPostByTranslatedSlug: any;
export type findPostByTranslatedSlug = any;
export const findTrackingCheckpoints: any;
export type findTrackingCheckpoints = any;
export const findUnique: any;
export type findUnique = any;
export const forget: any;
export type forget = any;
export const forgotPassword: any;
export type forgotPassword = any;
export const from: any;
export type from = any;
export const fullTextSearch: any;
export type fullTextSearch = any;
export const generateTokens: any;
export type generateTokens = any;
export const get: any;
export type get = any;
export const getActiveLanguages: any;
export type getActiveLanguages = any;
export const getAdministrativeService: any;
export type getAdministrativeService = any;
export const getAll: any;
export type getAll = any;
export const getAnalyticsService: any;
export type getAnalyticsService = any;
export const getApiKeyRepository: any;
export type getApiKeyRepository = any;
export const getAuditLog: any;
export type getAuditLog = any;
export const getAuditLogs: any;
export type getAuditLogs = any;
export const getAuditService: any;
export type getAuditService = any;
export const getAuditStats: any;
export type getAuditStats = any;
export const getAuthService: any;
export type getAuthService = any;
export const getAvailableCustomers: any;
export type getAvailableCustomers = any;
export const getAvailableEvents: any;
export type getAvailableEvents = any;
export const getAvailableTransitions: any;
export type getAvailableTransitions = any;
export const getBatchTranslationStatus: any;
export type getBatchTranslationStatus = any;
export const getBulkActionService: any;
export type getBulkActionService = any;
export const getCategory: any;
export type getCategory = any;
export const getCategoryService: any;
export type getCategoryService = any;
export const getCategoryTree: any;
export type getCategoryTree = any;
export const getComment: any;
export type getComment = any;
export const getCommentService: any;
export type getCommentService = any;
export const getContactService: any;
export type getContactService = any;
export const getCountries: any;
export type getCountries = any;
export const getCustomFieldService: any;
export type getCustomFieldService = any;
export const getCustomer: any;
export type getCustomer = any;
export const getCustomerAuthService: any;
export type getCustomerAuthService = any;
export const getCustomerGroup: any;
export type getCustomerGroup = any;
export const getCustomerGroupService: any;
export type getCustomerGroupService = any;
export const getCustomerPackageService: any;
export type getCustomerPackageService = any;
export const getCustomerReceiverService: any;
export type getCustomerReceiverService = any;
export const getCustomerRepository: any;
export type getCustomerRepository = any;
export const getCustomerSenderService: any;
export type getCustomerSenderService = any;
export const getCustomerService: any;
export type getCustomerService = any;
export const getCustomerTokenService: any;
export type getCustomerTokenService = any;
export const getDashboardStats: any;
export type getDashboardStats = any;
export const getDatabaseMaintenanceService: any;
export type getDatabaseMaintenanceService = any;
export const getDefaultLanguage: any;
export type getDefaultLanguage = any;
export const getDetail: any;
export type getDetail = any;
export const getDeviceTokenService: any;
export type getDeviceTokenService = any;
export const getExportService: any;
export type getExportService = any;
export const getFieldBoxes: any;
export type getFieldBoxes = any;
export const getFieldsForContext: any;
export type getFieldsForContext = any;
export const getFile: any;
export type getFile = any;
export const getFolder: any;
export type getFolder = any;
export const getFolderTree: any;
export type getFolderTree = any;
export const getForCategory: any;
export type getForCategory = any;
export const getForPage: any;
export type getForPage = any;
export const getForPost: any;
export type getForPost = any;
export const getForTag: any;
export type getForTag = any;
export const getGroup: any;
export type getGroup = any;
export const getHsCodeService: any;
export type getHsCodeService = any;
export const getImportService: any;
export type getImportService = any;
export const getLanguageById: any;
export type getLanguageById = any;
export const getLanguageRepository: any;
export type getLanguageRepository = any;
export const getLanguageService: any;
export type getLanguageService = any;
export const getLanguages: any;
export type getLanguages = any;
export const getMany: any;
export type getMany = any;
export const getMediaFileService: any;
export type getMediaFileService = any;
export const getMediaFolderService: any;
export type getMediaFolderService = any;
export const getMembers: any;
export type getMembers = any;
export const getNotificationService: any;
export type getNotificationService = any;
export const getNotificationSettingService: any;
export type getNotificationSettingService = any;
export const getNotificationTemplateService: any;
export type getNotificationTemplateService = any;
export const getOrderRepository: any;
export type getOrderRepository = any;
export const getOrderService: any;
export type getOrderService = any;
export const getPackingService: any;
export type getPackingService = any;
export const getPackingType: any;
export type getPackingType = any;
export const getPage: any;
export type getPage = any;
export const getPageBySlug: any;
export type getPageBySlug = any;
export const getPageService: any;
export type getPageService = any;
export const getPartner: any;
export type getPartner = any;
export const getPartnerService: any;
export type getPartnerService = any;
export const getPost: any;
export type getPost = any;
export const getPostBySlug: any;
export type getPostBySlug = any;
export const getPostService: any;
export type getPostService = any;
export const getPreferences: any;
export type getPreferences = any;
export const getRateCardRepository: any;
export type getRateCardRepository = any;
export const getRateCardService: any;
export type getRateCardService = any;
export const getRelatedLanguageItems: any;
export type getRelatedLanguageItems = any;
export const getRelatedPosts: any;
export type getRelatedPosts = any;
export const getRequestLogs: any;
export type getRequestLogs = any;
export const getRequestStats: any;
export type getRequestStats = any;
export const getRevision: any;
export type getRevision = any;
export const getRevisionService: any;
export type getRevisionService = any;
export const getRevisions: any;
export type getRevisions = any;
export const getRole: any;
export type getRole = any;
export const getRoleService: any;
export type getRoleService = any;
export const getRow: any;
export type getRow = any;
export const getRuleGroups: any;
export type getRuleGroups = any;
export const getScheduledNotificationService: any;
export type getScheduledNotificationService = any;
export const getSeoMetaService: any;
export type getSeoMetaService = any;
export const getService: any;
export type getService = any;
export const getSettingService: any;
export type getSettingService = any;
export const getStats: any;
export type getStats = any;
export const getStatusCounts: any;
export type getStatusCounts = any;
export const getSubmission: any;
export type getSubmission = any;
export const getSystemDiagnosticsService: any;
export type getSystemDiagnosticsService = any;
export const getSystemInfo: any;
export type getSystemInfo = any;
export const getTag: any;
export type getTag = any;
export const getTagService: any;
export type getTagService = any;
export const getTemplateById: any;
export type getTemplateById = any;
export const getTheme: any;
export type getTheme = any;
export const getTime: any;
export type getTime = any;
export const getTopupTransactionService: any;
export type getTopupTransactionService = any;
export const getTranslation: any;
export type getTranslation = any;
export const getTranslationService: any;
export type getTranslationService = any;
export const getTranslationStatus: any;
export type getTranslationStatus = any;
export const getTransportModes: any;
export type getTransportModes = any;
export const getTree: any;
export type getTree = any;
export const getUnreadCount: any;
export type getUnreadCount = any;
export const getUser: any;
export type getUser = any;
export const getUserManagementService: any;
export type getUserManagementService = any;
export const getUserWithPermissions: any;
export type getUserWithPermissions = any;
export const getWebhook: any;
export type getWebhook = any;
export const getWebhookLogs: any;
export type getWebhookLogs = any;
export const getWebhookService: any;
export type getWebhookService = any;
export const getWorkflowService: any;
export type getWorkflowService = any;
export const gt: any;
export type gt = any;
export const has: any;
export type has = any;
export const heartbeat: any;
export type heartbeat = any;
export const hsCodeFeatures: any;
export type hsCodeFeatures = any;
export const importCategories: any;
export type importCategories = any;
export const importContent: any;
export type importContent = any;
export const importGroups: any;
export type importGroups = any;
export const importPages: any;
export type importPages = any;
export const importPosts: any;
export type importPosts = any;
export const importSettings: any;
export type importSettings = any;
export const importTags: any;
export type importTags = any;
export const includes: any;
export type includes = any;
export const info: any;
export type info = any;
export const input: any;
export type input = any;
export const invalidate: any;
export type invalidate = any;
export const invalidateRateCardCache: any;
export type invalidateRateCardCache = any;
export const isArray: any;
export type isArray = any;
export const isNaN: any;
export type isNaN = any;
export const join: any;
export type join = any;
export const list: any;
export type list = any;
export const listAllCustomerGroups: any;
export type listAllCustomerGroups = any;
export const listBlacklist: any;
export type listBlacklist = any;
export const listCategories: any;
export type listCategories = any;
export const listComments: any;
export type listComments = any;
export const listCustomerGroups: any;
export type listCustomerGroups = any;
export const listCustomers: any;
export type listCustomers = any;
export const listFiles: any;
export type listFiles = any;
export const listFolders: any;
export type listFolders = any;
export const listGroups: any;
export type listGroups = any;
export const listNotifications: any;
export type listNotifications = any;
export const listPages: any;
export type listPages = any;
export const listPartners: any;
export type listPartners = any;
export const listPermissions: any;
export type listPermissions = any;
export const listPosts: any;
export type listPosts = any;
export const listRevisions: any;
export type listRevisions = any;
export const listRoles: any;
export type listRoles = any;
export const listServices: any;
export type listServices = any;
export const listSubmissions: any;
export type listSubmissions = any;
export const listTags: any;
export type listTags = any;
export const listTemplates: any;
export type listTemplates = any;
export const listTranslations: any;
export type listTranslations = any;
export const listUsers: any;
export type listUsers = any;
export const listVerificationCodes: any;
export type listVerificationCodes = any;
export const listWebhooks: any;
export type listWebhooks = any;
export const literal: any;
export type literal = any;
export const login: any;
export type login = any;
export const lt: any;
export type lt = any;
export const mapToAdminOrderDetailResponse: any;
export type mapToAdminOrderDetailResponse = any;
export const mapToAdminOrderSummaryResponse: any;
export type mapToAdminOrderSummaryResponse = any;
export const markAllRead: any;
export type markAllRead = any;
export const markRead: any;
export type markRead = any;
export const markReplied: any;
export type markReplied = any;
export const markSpam: any;
export type markSpam = any;
export const match: any;
export type match = any;
export const moveFiles: any;
export type moveFiles = any;
export const mutation: any;
export type mutation = any;
export const nativeEnum: any;
export type nativeEnum = any;
export const notify: any;
export type notify = any;
export const now: any;
export type now = any;
export const nullable: any;
export type nullable = any;
export const number: any;
export type number = any;
export const object: any;
export type object = any;
export const onDefaultCardApproved: any;
export type onDefaultCardApproved = any;
export const optional: any;
export type optional = any;
export const overlayCategoryTranslations: any;
export type overlayCategoryTranslations = any;
export const overlayPageTranslation: any;
export type overlayPageTranslation = any;
export const overlayPageTranslations: any;
export type overlayPageTranslations = any;
export const overlayPostTranslation: any;
export type overlayPostTranslation = any;
export const overlayPostTranslations: any;
export type overlayPostTranslations = any;
export const overlayTagTranslations: any;
export type overlayTagTranslations = any;
export const parseInt: any;
export type parseInt = any;
export const partial: any;
export type partial = any;
export const permanentlyDeletePost: any;
export type permanentlyDeletePost = any;
export const permanentlyDeleteTag: any;
export type permanentlyDeleteTag = any;
export const pipeline: any;
export type pipeline = any;
export const plus: any;
export type plus = any;
export const previewTemplate: any;
export type previewTemplate = any;
export const prisma: any;
export type prisma = any;
export const publishPost: any;
export type publishPost = any;
export const purgeAllAuditLogs: any;
export type purgeAllAuditLogs = any;
export const purgeAuditLogs: any;
export type purgeAuditLogs = any;
export const purgeRequestLogs: any;
export type purgeRequestLogs = any;
export const push: any;
export type push = any;
export const query: any;
export type query = any;
export const recalculateOrderFees: any;
export type recalculateOrderFees = any;
export const record: any;
export type record = any;
export const recordView: any;
export type recordView = any;
export const register: any;
export type register = any;
export const registerEventListeners: any;
export type registerEventListeners = any;
export const registerToken: any;
export type registerToken = any;
export const release: any;
export type release = any;
export const remember: any;
export type remember = any;
export const removeFromBlacklist: any;
export type removeFromBlacklist = any;
export const removeFromBlacklistBulk: any;
export type removeFromBlacklistBulk = any;
export const removeItem: any;
export type removeItem = any;
export const removeMembers: any;
export type removeMembers = any;
export const replace: any;
export type replace = any;
export const replaceSlabs: any;
export type replaceSlabs = any;
export const resetPassword: any;
export type resetPassword = any;
export const responseCache: any;
export type responseCache = any;
export const restoreCategory: any;
export type restoreCategory = any;
export const restorePost: any;
export type restorePost = any;
export const restoreTag: any;
export type restoreTag = any;
export const rotateWebhookSecret: any;
export type rotateWebhookSecret = any;
export const round: any;
export type round = any;
export const saveContentLanguage: any;
export type saveContentLanguage = any;
export const saveForCategory: any;
export type saveForCategory = any;
export const saveForPage: any;
export type saveForPage = any;
export const saveForPost: any;
export type saveForPost = any;
export const saveForTag: any;
export type saveForTag = any;
export const saveModelFields: any;
export type saveModelFields = any;
export const saveTranslation: any;
export type saveTranslation = any;
export const scan: any;
export type scan = any;
export const search: any;
export type search = any;
export const sendDirectEmail: any;
export type sendDirectEmail = any;
export const sendVerificationCode: any;
export type sendVerificationCode = any;
export const set: any;
export type set = any;
export const setCustomerPassword: any;
export type setCustomerPassword = any;
export const setDefaultLanguage: any;
export type setDefaultLanguage = any;
export const setTheme: any;
export type setTheme = any;
export const slice: any;
export type slice = any;
export const split: any;
export type split = any;
export const string: any;
export type string = any;
export const stringify: any;
export type stringify = any;
export const superRefine: any;
export type superRefine = any;
export const syncCacheBulk: any;
export type syncCacheBulk = any;
export const syncPermissions: any;
export type syncPermissions = any;
export const syncRoles: any;
export type syncRoles = any;
export const testConnection: any;
export type testConnection = any;
export const toFixed: any;
export type toFixed = any;
export const toLowerCase: any;
export type toLowerCase = any;
export const toggleSuperAdmin: any;
export type toggleSuperAdmin = any;
export const trash: any;
export type trash = any;
export const trim: any;
export type trim = any;
export const unknown: any;
export type unknown = any;
export const unregisterToken: any;
export type unregisterToken = any;
export const update: any;
export type update = any;
export const updateBlacklistReason: any;
export type updateBlacklistReason = any;
export const updateCategory: any;
export type updateCategory = any;
export const updateCustomer: any;
export type updateCustomer = any;
export const updateCustomerGroup: any;
export type updateCustomerGroup = any;
export const updateFile: any;
export type updateFile = any;
export const updateFolder: any;
export type updateFolder = any;
export const updateGroup: any;
export type updateGroup = any;
export const updateItem: any;
export type updateItem = any;
export const updateLanguage: any;
export type updateLanguage = any;
export const updateOrderStatus: any;
export type updateOrderStatus = any;
export const updatePage: any;
export type updatePage = any;
export const updatePartner: any;
export type updatePartner = any;
export const updatePost: any;
export type updatePost = any;
export const updatePreference: any;
export type updatePreference = any;
export const updateProfile: any;
export type updateProfile = any;
export const updateRole: any;
export type updateRole = any;
export const updateService: any;
export type updateService = any;
export const updateStatus: any;
export type updateStatus = any;
export const updateTag: any;
export type updateTag = any;
export const updateTemplate: any;
export type updateTemplate = any;
export const updateUser: any;
export type updateUser = any;
export const updateWebhook: any;
export type updateWebhook = any;
export const use: any;
export type use = any;
export const validateDateRange: any;
export type validateDateRange = any;
export const validatePublishingConstraints: any;
export type validatePublishingConstraints = any;
export const validateSlabs: any;
export type validateSlabs = any;
export const validateStartDateNotPast: any;
export type validateStartDateNotPast = any;
export const verifyAccessToken: any;
export type verifyAccessToken = any;
export const verifyCustomerEmail: any;
export type verifyCustomerEmail = any;
export const verifyEmailByToken: any;
export type verifyEmailByToken = any;
export const verifyRefreshToken: any;
export type verifyRefreshToken = any;
export const warn: any;
export type warn = any;
export const writeBuffer: any;
export type writeBuffer = any;

export namespace Prisma {
  export type DbNull = any;
  export const DbNull: any;
  export type Decimal = any;
  export const Decimal: any;
  export type InputJsonValue = any;
  export const InputJsonValue: any;
  export type JsonValue = any;
  export const JsonValue: any;
  export type OrderImportWhereInput = any;
  export const OrderImportWhereInput: any;
  export type SortOrder = any;
  export const SortOrder: any;
  export type TransactionClient = any;
  export const TransactionClient: any;
}
export const Prisma: any;
