import { router } from "../../../trpc";
import {
  adjustTopupRequest,
  approveTopupRequest,
  cancelTopupRequest,
  createTopupRequest,
  exportExcel,
  exportTransactionExcel,
  getLatestExchangeRate,
  getPaymentMethods,
  getTopupHistory,
  getTransactionHistory,
  getWalletSummary,
  updateTopupRequest,
  payOrderWithWallet,
} from "./procedures/topup.handler";

export const customerTopupRouter = router({
  getWalletSummary,
  getPaymentMethods,
  getLatestExchangeRate,
  getHistory: getTopupHistory,
  getTopupHistory,
  getTransactionHistory,
  create: createTopupRequest,
  createTopupRequest,
  update: updateTopupRequest,
  updateTopupRequest,
  cancel: cancelTopupRequest,
  cancelTopupRequest,
  adjust: adjustTopupRequest,
  adjustTopupRequest,
  approve: approveTopupRequest,
  approveTopupRequest,
  payOrderWithWallet,
  exportExcel,
  exportTransactionExcel,
});
