name: Publish @flash-ship/ecom-ui Package to GitHub Packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
          scope: '@flash-ship'

      - name: Enable Corepack & Install Dependencies
        run: |
          corepack enable
          yarn install

      - name: Type-check @flash-ship/ecom-ui
        run: yarn --cwd ./packages/ui type-check

      - name: Build @flash-ship/ecom-ui
        run: yarn --cwd ./packages/ui build

      - name: Publish Package to GitHub Packages
        run: |
          cd packages/ui
          npm publish --access restricted || echo "Package version already published."
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
